name: Npm Publish

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ref: master
      - name: Use Node
        uses: actions/setup-node@v3
        with:
            node-version: '16.x'
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
